pif: Add message to static_assert for C11 compliance, fix build with gcc 8
Seen with gcc 8.5:

---
In file included from passt.h:18,
                 from qrap.c:36:
pif.h: In function 'pif_type':
pif.h:48:44: error: expected ',' before ')' token
  static_assert(sizeof("?") <= PIF_NAME_SIZE);
                                            ^
make: *** [Makefile:105: qrap] Error 1
---

As noted in ba84a3b17af8 ("treewide: Add messages to static_assert()
calls"), static_assert() calls need a message to comply with C11. The
form without message is supported starting from C23 only.

Fixes: cbcd4284111f ("pif: Limit pif names to 128 bytes")
Signed-off-by: Stefano Brivio <sbrivio@redhat.com>
Reviewed-by: David Gibson <david@gibson.dropbear.id.au>